<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\pmnbd\models\blog;

use Yii;
use common\models\Subdomen;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "blog_post_tag".
 *
 * @property integer $blog_post_id
 * @property integer $subdomen_id
 *
 * @property \backend\modules\pmnbd\models\blog\BlogPost $blogPost
 * @property common\models\Subdomen $subdomen
 * @property string $aliasModel
 */

class BlogPostSubdomen extends \yii\db\ActiveRecord
{

    use \common\utility\SortableTrait;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return
            ArrayHelper::merge(
                [],
                $this->sortableModelBehavior()
            );
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog_post_subdomen';
    }

    public static function primaryKey()
    {
        return ['blog_post_id', 'subdomen_id'];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['blog_post_id', 'subdomen_id'], 'integer'],
            [['blog_post_id', 'subdomen_id'], 'unique', 'targetAttribute' => ['blog_post_id', 'subdomen_id']],
            [['blog_post_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\pmnbd\models\blog\BlogPost::className(), 'targetAttribute' => ['blog_post_id' => 'id']],
            [['subdomen_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Subdomen::className(), 'targetAttribute' => ['subdomen_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'blog_post_id' => Yii::t('models', 'Blog Post ID'),
            'subdomen_id' => Yii::t('models', 'Subdomen ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBlogPost()
    {
        return $this->hasOne(\backend\modules\pmnbd\models\blog\BlogPost::className(), ['id' => 'blog_post_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubdomen()
    {
        return $this->hasOne(\common\models\Subdomen::className(), ['id' => 'subdomen_id']);
    }

}
